# Generated by Django 5.1.1 on 2024-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='image',
            field=models.ImageField(default='static/assets/image/image-not-found.png', upload_to='product_images/'),
        ),
    ]
