# Generated by Django 5.1.1 on 2024-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(default='media/product_images/image-not-found.png', upload_to='product_images/'),
        ),
    ]
