# Generated by Django 5.1.1 on 2024-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(default='product_images/image-not-found.png', upload_to='product_images/'),
        ),
    ]
